### ISSUE TITLE
Add fainter pink to complete circle for character  limit

### ISSUE THREAD

**Issue by will-weiss** [morehumaninternet/roar-extension#103]
## Context

When the extension first loads the character limit has a tiny sliver of the circle filled. We should use a fainter pink to complete the circle, which twitter does.

<img width="732" alt="image" src="https://user-images.githubusercontent.com/6589960/100802581-b4e86580-33f7-11eb-86a4-c43a0b938d8d.png">

**Comment by shachar-langer** [comment]
I used [this](https://medium.com/@pppped/how-to-code-a-responsive-circular-percentage-chart-with-svg-and-css-3632f8cd7705) article to create the current functionality. I think the answer to the requested functionality is in there somewhere.

**Comment by hankeliu2015** [comment]
@will-weiss the code change you made tested on local, working great.
