### ISSUE TITLE
Add a logout button

### ISSUE THREAD

**Issue by shachar-langer** [morehumaninternet/roar-extension#41]
## Context

Users log in to the extension using Twitter. We need to add a logout option.

## Possible solution

A dropdown menu on the avatar image with a "logout" option:
![image](https://user-images.githubusercontent.com/9791009/99288916-90f42400-283c-11eb-83c1-c1544e8d50b3.png)

## Steps

- [ ] Add a beautiful human logout button.
- [ ] Call the [server endpoint](https://github.com/morehumaninternet/roar-server/issues/14) to logout.
- [ ] Once the user logs out, redirect to the [not-authed](https://github.com/morehumaninternet/roar-extension/blob/main/src/popup/views/not-authed.tsx) page by creating a [new action](https://github.com/morehumaninternet/roar-extension/blob/main/src/background/responders.ts#L42) and updating the [auth state](https://github.com/morehumaninternet/roar-extension/blob/main/src/types.ts#L57) in the store.

**Comment by hankeliu2015** [comment]
work in progress under [logout-button branch](https://github.com/morehumaninternet/roar-extension/tree/logout-button).
