### ISSUE TITLE
Style the sign in page

### ISSUE THREAD

**Issue by shachar-langer** [morehumaninternet/roar-extension#55]
## Context

When the user first opens the extension, there's a sign-in with Twitter [button](https://github.com/morehumaninternet/roar-extension/blob/main/src/popup/views/not-authed.tsx#L4). We should style this page to look like this:
![image](https://user-images.githubusercontent.com/9791009/99414130-ceb58300-28f6-11eb-99c1-bad0ffb6d5dc.png)

## Steps

- [ ] Edit the not-authed [file](https://github.com/morehumaninternet/roar-extension/blob/main/src/popup/views/not-authed.tsx#L4) and add the Roar icon SVG, the "Log in with Twitter" SVG, and text at the bottom. The "morehumaninternet.org" should be a link to [morehumaninternet.org](https://morehumaninternet.org/).
- [ ] Add a new SCSS file [here](https://github.com/morehumaninternet/roar-extension/tree/main/scss/components), style the page and @use it from the [main](https://github.com/morehumaninternet/roar-extension/blob/main/scss/popup.scss) SCSS file.

**Comment by hankeliu2015** [comment]
ready for a review <https://github.com/morehumaninternet/roar-extension/tree/sign-in-page-style>
