### ISSUE TITLE
Add a default avatar image

### ISSUE THREAD

**Issue by shachar-langer** [morehumaninternet/roar-extension#56]
## Context

When a user without a profile image logs in to the extension, the avatar image is broken:
![image](https://user-images.githubusercontent.com/9791009/99417084-cf9be400-28f9-11eb-9adc-775bd93998d6.png)
We should instead show Twitter's default profile image.

## Steps

- [ ] Add a default avatar image to the image [folder](https://github.com/morehumaninternet/roar-extension/tree/main/img) and delete the old avatar.png image.
- [ ] Set the new path to the image in the [code](https://github.com/morehumaninternet/roar-extension/blob/main/src/popup/views/authenticated.tsx#L42).

**Comment by hankeliu2015** [comment]
Add current Twitter profile default avatar file into /img folder and remove old avatar.png file. In authenticated.tsx file, img src file already set to default-avatar.png. 
![Screen Shot 2020-11-24 at 4 47 50 PM](https://user-images.githubusercontent.com/16155615/100155425-40507c80-2e75-11eb-9340-d1dcd342c950.png)

**Comment by hankeliu2015** [comment]
Tested with a new twitter account with default avatar profile, all worked.
